### ISSUE TITLE
monsterinfo issue

### ISSUE THREAD

**Issue by changchang4825** [changchang4825/OSS19#2]
@eeassn 
1. myPokemon의 모든 skill_point를 양수로 설정 부탁 드립니다.
2. 모든 skill name이 대문자로 시작하도록 설정 부탁 드립니다.
3. damage가 0으로 설정되어 있는 스킬 변경 부탁 드립니다.

**Comment by eeassn** [comment]
1. 수정완료
2. 수정완료
3. 공스킬 and 버프스킬 and 공격반사 > 일반 공격스킬 & 회복스킬

**Comment by changchang4825** [comment]
확인했습니다.
monsterInfo.js 내용을 battle.js로 옮기겠습니다.
